use serde::Serialize;

#[derive(Serialize, Clone, Debug, PartialEq)]
pub enum Manufacturer {
    Riedel,
    Audinate,
    Yamaha,
    Merging,
    Lawo,
    DirectOut,
    Digico,
    SSL,
    AllenHeath,
    QSC,
    Avid,
    AxiaTelos,
    Wheatstone,
    RossVideo,
    Evertz,
    GrassValley,
    TSL,
    Calrec,
    ClearCom,
    RTS,
    Shure,
    Sennheiser,
    AudioTechnica,
    BirdDog,
    BlackmagicDesign,
    Focusrite,
    Genelec,
    Studer,
    Sonifex,
    Neumann,
    Apogee,
    BehringerMidas,
    SoundDevices,
    Luminex,
    NetgearAV,
    DBAudiotechnik,
    LAco,
    MeyerSound,
    KlarkTeknik,
    Kramer,
    ATEN,
    Unknown,
}

impl Manufacturer {
    pub fn to_string(&self) -> String {
        match self {
            Manufacturer::Riedel => "Riedel".to_string(),
            Manufacturer::Audinate => "Audinate".to_string(),
            Manufacturer::Yamaha => "Yamaha".to_string(),
            Manufacturer::Merging => "Merging".to_string(),
            Manufacturer::Lawo => "Lawo".to_string(),
            Manufacturer::DirectOut => "DirectOut".to_string(),
            Manufacturer::Digico => "Digico".to_string(),
            Manufacturer::SSL => "SSL".to_string(),
            Manufacturer::AllenHeath => "Allen & Heath".to_string(),
            Manufacturer::QSC => "QSC".to_string(),
            Manufacturer::Avid => "Avid".to_string(),
            Manufacturer::AxiaTelos => "Axia/Telos".to_string(),
            Manufacturer::Wheatstone => "Wheatstone".to_string(),
            Manufacturer::RossVideo => "Ross Video".to_string(),
            Manufacturer::Evertz => "Evertz".to_string(),
            Manufacturer::GrassValley => "Grass Valley".to_string(),
            Manufacturer::TSL => "TSL".to_string(),
            Manufacturer::Calrec => "Calrec".to_string(),
            Manufacturer::ClearCom => "Clear-Com".to_string(),
            Manufacturer::RTS => "RTS".to_string(),
            Manufacturer::Shure => "Shure".to_string(),
            Manufacturer::Sennheiser => "Sennheiser".to_string(),
            Manufacturer::AudioTechnica => "Audio-Technica".to_string(),
            Manufacturer::BirdDog => "BirdDog".to_string(),
            Manufacturer::BlackmagicDesign => "Blackmagic Design".to_string(),
            Manufacturer::Focusrite => "Focusrite".to_string(),
            Manufacturer::Genelec => "Genelec".to_string(),
            Manufacturer::Studer => "Studer".to_string(),
            Manufacturer::Sonifex => "Sonifex".to_string(),
            Manufacturer::Neumann => "Neumann".to_string(),
            Manufacturer::Apogee => "Apogee".to_string(),
            Manufacturer::BehringerMidas => "Behringer/Midas".to_string(),
            Manufacturer::SoundDevices => "Sound Devices".to_string(),
            Manufacturer::Luminex => "Luminex".to_string(),
            Manufacturer::NetgearAV => "Netgear AV".to_string(),
            Manufacturer::DBAudiotechnik => "d&b audiotechnik".to_string(),
            Manufacturer::LAco => "L-Acoustics".to_string(),
            Manufacturer::MeyerSound => "Meyer Sound".to_string(),
            Manufacturer::KlarkTeknik => "Klark Teknik".to_string(),
            Manufacturer::Kramer => "Kramer".to_string(),
            Manufacturer::ATEN => "ATEN".to_string(),
            Manufacturer::Unknown => "Unknown".to_string(),
        }
    }

    pub fn default_timeout_ms(&self, unknown_timeout_s: u64) -> u64 {
        match self {
            Manufacturer::Riedel => 12_000,
            Manufacturer::Audinate => 35_000,
            Manufacturer::Yamaha => 35_000,
            Manufacturer::Merging => 35_000,
            Manufacturer::Lawo => 35_000,
            Manufacturer::DirectOut => 35_000,
            Manufacturer::Digico => 35_000,
            Manufacturer::SSL => 35_000,
            Manufacturer::AllenHeath => 35_000,
            Manufacturer::QSC => 35_000,
            Manufacturer::Avid => 35_000,
            Manufacturer::AxiaTelos => 35_000,
            Manufacturer::Wheatstone => 35_000,
            Manufacturer::RossVideo => 40_000,
            Manufacturer::Evertz => 40_000,
            Manufacturer::GrassValley => 40_000,
            Manufacturer::TSL => 40_000,
            Manufacturer::Calrec => 40_000,
            Manufacturer::ClearCom => 40_000,
            Manufacturer::RTS => 40_000,
            Manufacturer::Shure => 35_000,
            Manufacturer::Sennheiser => 35_000,
            Manufacturer::AudioTechnica => 35_000,
            Manufacturer::BirdDog => 40_000,
            Manufacturer::BlackmagicDesign => 40_000,
            Manufacturer::Focusrite => 35_000,
            Manufacturer::Genelec => 35_000,
            Manufacturer::Studer => 35_000,
            Manufacturer::Sonifex => 35_000,
            Manufacturer::Neumann => 35_000,
            Manufacturer::Apogee => 35_000,
            Manufacturer::BehringerMidas => 35_000,
            Manufacturer::SoundDevices => 35_000,
            Manufacturer::Luminex => 40_000,
            Manufacturer::NetgearAV => 40_000,
            Manufacturer::DBAudiotechnik => 40_000,
            Manufacturer::LAco => 40_000,
            Manufacturer::MeyerSound => 40_000,
            Manufacturer::KlarkTeknik => 35_000,
            Manufacturer::Kramer => 35_000,
            Manufacturer::ATEN => 35_000,
            Manufacturer::Unknown => unknown_timeout_s.max(60) * 1000,
        }
    }
}

pub fn identify_manufacturer(mac: &str) -> Manufacturer {
    let clean_mac = mac
        .replace(|c: char| !c.is_alphanumeric(), "")
        .to_uppercase();
    if clean_mac.len() < 6 {
        return Manufacturer::Unknown;
    }
    let oui = &clean_mac[0..6];

    match oui {
        "001ACA" | "A80000" => Manufacturer::Riedel,
        "001DC1" => Manufacturer::Audinate,
        "00A0DE" => Manufacturer::Yamaha,
        "D83ADD" => Manufacturer::NetgearAV, // Table OUI source : NetgearAV mapping
        "001564" => Manufacturer::Merging,
        "00907F" => Manufacturer::Lawo,
        "001E4C" => Manufacturer::DirectOut,
        "000C6E" => Manufacturer::Digico,
        "000B8C" => Manufacturer::SSL,
        "001B66" => Manufacturer::AllenHeath,
        "90E2BA" => Manufacturer::QSC,
        "00055D" => Manufacturer::Avid,
        "00900B" => Manufacturer::AxiaTelos,
        "0014C2" => Manufacturer::Wheatstone,
        "001CCC" => Manufacturer::RossVideo,
        "0005CA" => Manufacturer::Evertz,
        "000DEC" => Manufacturer::GrassValley,
        "000F72" => Manufacturer::TSL,
        "001D78" => Manufacturer::Calrec,
        "001A1E" => Manufacturer::ClearCom,
        "00136F" => Manufacturer::RTS,
        "0024BE" => Manufacturer::Shure,
        "000462" => Manufacturer::Sennheiser,
        "00091F" => Manufacturer::AudioTechnica,
        "027F61" => Manufacturer::BirdDog,
        "E091F5" => Manufacturer::BlackmagicDesign,
        "000EEC" => Manufacturer::Focusrite,
        "000A8F" => Manufacturer::Genelec,
        "000A0E" => Manufacturer::Studer,
        "0090F5" => Manufacturer::Sonifex,
        "000AF3" => Manufacturer::Neumann,
        "00066A" => Manufacturer::Apogee,
        "001F7A" => Manufacturer::BehringerMidas,
        "00196B" => Manufacturer::SoundDevices,
        "001B55" => Manufacturer::Luminex,
        "00242C" => Manufacturer::DBAudiotechnik,
        "903EAB" => Manufacturer::LAco,
        "000D4B" => Manufacturer::MeyerSound,
        "0005A6" => Manufacturer::KlarkTeknik,
        "000F7C" => Manufacturer::Kramer,
        "000BF6" => Manufacturer::ATEN,
        _ => Manufacturer::Unknown,
    }
}
